name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    with:
      qmk_repo: vial-kb/vial-qmk
      qmk_ref: vial
      preparation_command: "cp -rf keyboards/* qmk_firmware/keyboards/"

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@ba76ce3d20f542d61c4c3d47c1d1d9e73b60a797
    if: always() && !cancelled()
    needs: build
